services:
  postgres:
    image: postgres:17-alpine
    container_name: sentinel-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sentinel-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  sentinel-net:
    name: sentinel-net