# Mosquitto — Sentinel-X : TLS + certificat client obligatoire, pas d'anonyme

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

per_listener_settings false
allow_anonymous false
acl_file /mosquitto/config/acl

listener 8883
tls_version tlsv1.2
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/mosquitto.crt
keyfile /mosquitto/certs/mosquitto.key
require_certificate true
use_identity_as_username true
